
package UniversidadULP.Vistas;

import UniversidadULP.AccesoADatos.MateriaData;
import UniversidadULP.Entidades.Materia;
import java.awt.Component;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Lourdes
 */
public class materiaView extends javax.swing.JInternalFrame {
private MateriaData matData = new MateriaData();
    private Materia matActual = null;
    /**
     * Creates new form materiaView
     */
    public materiaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        tfAnio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        cbEstado = new javax.swing.JCheckBox();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Codigo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 101, -1, -1));

        tfCodigo.setBackground(new java.awt.Color(255, 255, 255));
        tfCodigo.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 107, 180, -1));

        jbBuscar.setBackground(new java.awt.Color(51, 204, 255));
        jbBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 104, -1, -1));

        contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfAnio.setBackground(new java.awt.Color(255, 255, 255));
        tfAnio.setForeground(new java.awt.Color(0, 0, 0));
        contenedor.add(tfAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 196, 112, -1));

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nombre");
        contenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 147, -1, -1));

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.setForeground(new java.awt.Color(0, 0, 0));
        contenedor.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 153, 180, -1));

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Año");
        contenedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jbGuardar.setBackground(new java.awt.Color(51, 204, 255));
        jbGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        contenedor.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 390, -1, -1));

        jbSalir.setBackground(new java.awt.Color(0, 51, 255));
        jbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        contenedor.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materia");
        contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 35, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Estado");
        contenedor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 243, -1, -1));

        jbNuevo.setBackground(new java.awt.Color(51, 204, 255));
        jbNuevo.setForeground(new java.awt.Color(255, 255, 255));
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        contenedor.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 390, -1, -1));

        jbEliminar.setBackground(new java.awt.Color(51, 204, 255));
        jbEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        contenedor.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 390, -1, -1));

        cbEstado.setBackground(new java.awt.Color(255, 255, 255));
        cbEstado.setForeground(new java.awt.Color(255, 255, 255));
        contenedor.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 247, -1, -1));

        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.parseInt(tfCodigo.getText());
            matActual = matData.buscarMateria(id);
            if(matActual!=null){
                tfNombre.setText(matActual.getNombre());
                tfAnio.setText(Integer.toString(matActual.getAnioMateria()));
                cbEstado.setSelected(matActual.isActivo());
            }else{
                JOptionPane.showMessageDialog(this, "Materia no encontrada");
            }

        }catch(NumberFormatException ex){
            JOptionPane.showConfirmDialog(this, "Usted debe ingresar un número." + ex);
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        
        if(validarCamposVacios(contenedor)){
            JOptionPane.showConfirmDialog(this, "Debe llenar todos los datos.");
            return;
        }
        try{
            String nombre = tfNombre.getText();
            Integer anio = Integer.valueOf(tfAnio.getText());
            boolean estado = cbEstado.isSelected();

            if(matActual==null){
                matActual = new Materia(nombre,anio,estado);
                matData.guardarMateria(matActual);
                
            }else{
                matActual.setNombre(nombre);
                matActual.setAnioMateria(anio);
                matActual.setActivo(estado);
                matData.modificarMateria(matActual);
            }

        }catch(NumberFormatException ex){
            JOptionPane.showConfirmDialog(this, "Usted debe ingresar datos válidos." + ex);
        }
        

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();

    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos(contenedor);
        matActual = null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        try{
            int id = Integer.parseInt(tfCodigo.getText());
            matData.borrarMateria(id);
            JOptionPane.showMessageDialog(this, "borrado exitoso");

        }catch(NumberFormatException ex){
            JOptionPane.showConfirmDialog(this, "Usted debe ingresar un número." + ex);
        }
        limpiarCampos(contenedor);
    }//GEN-LAST:event_jbEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbEstado;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos(JPanel jpanel) {
        for (Component c : jpanel.getComponents()) {
            if (c instanceof JTextField) {
                JTextField t = (JTextField) c;
                t.setText("");
            }
            if(c instanceof JCheckBox){
                JCheckBox t = (JCheckBox) c;
                t.setSelected(false);
            }

        }
    }
    
    private boolean validarCamposVacios(JPanel jpanel) {
        for (Component c : jpanel.getComponents()) {
            if (c instanceof JTextField) {
                JTextField t = (JTextField) c;
                if (t.getText().trim().isEmpty()) {
                    return true; //devuelve true si hay algun campo vacio
                }
            }

        }
        return false; //devuelve false todos los campos estan llenos
    }
}


